Bump dependencies, switch to node16, and add simple smoke test (#6)
* chore: replace deprecated @zeit/ncc with @vercel/ncc

    warning @zeit/ncc@0.22.3: @zeit/ncc is no longer maintained. Please use @vercel/ncc instead.

* fix: missing typescript in devDependencies

    $ yarn build
    ...
    [1] ncc: Compiling file index.js into CJS
    [0] Error: Module build failed (from ./node_modules/@vercel/ncc/dist/ncc/loaders/ts-loader.js):
    [0] Error: Could not load TypeScript compiler with NPM package name `./node_modules/@vercel/ncc/dist/ncc/typescript.js`. Are you sure it is correctly installed?

* chore: bump @actions/github from 2.1.1 to 5.1.1

* fix: missing @types/node in devDependencies

    $ yarn build
    ...
    ncc: Using typescript@4.8.4 (local user-provided)
    Error: [tsl] ERROR in /home/jirutjak/action-post-run/post.ts(2,18)
          TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

* chore: bump concurrently from 5.2.0 to 7.5.0

* chore: update to node16

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Resolves #4

* chore: rebuild dist

* test: run simple smoke test on CI