fix: missing @types/node in devDependencies
    $ yarn build
    ...
    ncc: Using typescript@4.8.4 (local user-provided)
    Error: [tsl] ERROR in /home/jirutjak/action-post-run/post.ts(2,18)
          TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.